export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CLEAR_REGISTER_STATE = 'CLEAR_REGISTER_STATE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_LOGIN_STATE = 'CLEAR_LOGIN_STATE';

export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR';
export const CLEAR_CREATE_CONTACT_STATE = 'CLEAR_CREATE_CONTACT_STATE';

export const GET_CONTACT_LOADING = 'GET_CONTACT_LOADING';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_ERROR = 'GET_CONTACT_ERROR';

export const READ_CONTACT_LOADING = 'READ_CONTACT_LOADING';
export const READ_CONTACT_SUCCESS = 'READ_CONTACT_SUCCESS';
export const READ_CONTACT_ERROR = 'READ_CONTACT_ERROR';
export const CLEAR_READ_CONTACT_STATE = 'CLEAR_READ_CONTACT_STATE';

export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_ERROR = 'EDIT_CONTACT_ERROR';
export const CLEAR_EDIT_CONTACT_STATE = 'CLEAR_EDIT_CONTACT_STATE';

export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';
export const CLEAR_DELETE_CONTACT_STATE = 'CLEAR_DELETE_CONTACT_STATE';
